VALID_EMAIL = 'julia_qa@gmail.com'
VALID_PASSWORD = 'qwerty1234'
PET_NAME = 'Mef'
COMMENT = 'Such a cute pet!'
NEW_PET_NAME = 'Podvoh'
NEW_PET_AGE = '1'
EDIT_NAME = 'Kura'
EDIT_AGE = '4'
NEW_PET_PICTURE = 'C:/Users/julia/PycharmProjects/Selenium_UI_Pet/angry_chihuahua.png'
 